Fix MSVC compiler errors about ambiguous template overloads
Given the following code:

    template <const char* const s> void foo() { }
    template <char c> void foo() { }

    int main(int argc, const char* argv[])
    {
      foo<';'>();
      return 0;
    }

MSVC produces the following errors:

    main.cpp(11): error C2440: 'specialization' : cannot convert from 'char' to 'const char *const '
              Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or function-style cast
    main.cpp(11): error C2973: 'foo' : invalid template argument 'char'
              main.cpp(6) : see declaration of 'foo'
    main.cpp(11): error C2668: 'foo' : ambiguous call to overloaded function
              main.cpp(7): could be 'void foo<59>(void)'
              main.cpp(6): or       'void foo<59>(void)'
              while trying to match the argument list '(void)'

To work around this, I've renamed the overloads of exactly(), find_first(), and
count_interval() that take a char to resolve the ambiguity.